/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BeneficiariesImport } from './routes/beneficiaries'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TermsAndConditionsLazyImport = createFileRoute('/terms-and-conditions')()
const RefundPolicyLazyImport = createFileRoute('/refund-policy')()
const PrivacyPolicyLazyImport = createFileRoute('/privacy-policy')()

// Create/Update Routes

const TermsAndConditionsLazyRoute = TermsAndConditionsLazyImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/terms-and-conditions.lazy').then((d) => d.Route),
)

const RefundPolicyLazyRoute = RefundPolicyLazyImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/refund-policy.lazy').then((d) => d.Route))

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const BeneficiariesRoute = BeneficiariesImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-conditions': typeof TermsAndConditionsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficiaries'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficiaries'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/beneficiaries'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  RefundPolicyLazyRoute: typeof RefundPolicyLazyRoute
  TermsAndConditionsLazyRoute: typeof TermsAndConditionsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  RefundPolicyLazyRoute: RefundPolicyLazyRoute,
  TermsAndConditionsLazyRoute: TermsAndConditionsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/beneficiaries",
        "/privacy-policy",
        "/refund-policy",
        "/terms-and-conditions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/beneficiaries": {
      "filePath": "beneficiaries.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.tsx"
    },
    "/refund-policy": {
      "filePath": "refund-policy.lazy.tsx"
    },
    "/terms-and-conditions": {
      "filePath": "terms-and-conditions.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
